/*
Shijun Jiang
CSCI 4125 Fall 2023
Phase4
*/

DROP TABLE REVIEW CASCADE CONSTRAINTS;
DROP TABLE LINEITEM CASCADE CONSTRAINTS;
DROP TABLE ORDERS CASCADE CONSTRAINTS;
DROP TABLE ADDRESS CASCADE CONSTRAINTS;
DROP TABLE CUSTOMER CASCADE CONSTRAINTS;
DROP TABLE PRODUCT CASCADE CONSTRAINTS;

CREATE TABLE PRODUCT (
    P_ID CHAR(3),
    P_Name VARCHAR(50) NOT NULL,
    P_Price DECIMAL(5, 2) NOT NULL,
    CONSTRAINT ProductPK PRIMARY KEY (P_ID)
);

CREATE TABLE CUSTOMER (
    C_ID CHAR(3),
    C_Name VARCHAR(50) NOT NULL,
    C_DateOfBirth DATE NOT NULL,
    C_ReferrerID CHAR(3),
    CONSTRAINT CustomerPK PRIMARY KEY (C_ID),
    CONSTRAINT CustomerFK FOREIGN KEY (C_ReferrerID) REFERENCES CUSTOMER(C_ID)
);

CREATE TABLE ORDERS (
    O_OrderNumber CHAR(5),
    O_OrderDate DATE NOT NULL,
    O_CustID CHAR(3),
    CONSTRAINT OrdersPK PRIMARY KEY (O_OrderNumber),
    CONSTRAINT OrdersFK FOREIGN KEY (O_CustID) REFERENCES CUSTOMER(C_ID)
);

CREATE TABLE LINEITEM (
    L_OrderNumber CHAR(5),
    L_ProductID CHAR(3),
    L_Quantity INT NOT NULL,
    CONSTRAINT LineItemPK PRIMARY KEY (L_OrderNumber, L_ProductID),
    CONSTRAINT LineItemOrderFK FOREIGN KEY (L_OrderNumber) REFERENCES ORDERS(O_OrderNumber),
    CONSTRAINT LineItemProductFK FOREIGN KEY (L_ProductID) REFERENCES PRODUCT(P_ID)
);

CREATE TABLE REVIEW (
    R_ProductID CHAR(3),
    R_Number INT,
    R_Rating INT NOT NULL,
    R_Text VARCHAR(250),
    CONSTRAINT ReviewPK PRIMARY KEY (R_ProductID, R_Number),
    CONSTRAINT ReviewProductFK FOREIGN KEY (R_ProductID) REFERENCES PRODUCT(P_ID)
);

CREATE TABLE ADDRESS (
    A_CustID CHAR(3),
    A_Address VARCHAR(300) NOT NULL,
    CONSTRAINT AddressPK PRIMARY KEY (A_CustID, A_Address),
    CONSTRAINT AddressCustomerFK FOREIGN KEY (A_CustID) REFERENCES CUSTOMER(C_ID)
);
