INSERT INTO product VALUES('P01','Taylor Swift Ticket',199.99);
INSERT INTO product VALUES('P02','Database Textbook',75.25);
INSERT INTO product VALUES('P03','Beignet Mix',3.49);
INSERT INTO product VALUES('P04','Pralines',9.99);
INSERT INTO product VALUES('P05','Crystal Hot Sauce',3.49);
INSERT INTO product VALUES('P06','Harry Styles Ticket',65.99);
INSERT INTO product VALUES('P07','Lizzo Ticket',150.99);
INSERT INTO product VALUES('P08','Tony Chachere''s',3.29);
INSERT INTO product VALUES('P09','Coffee',4.10);
INSERT INTO product VALUES('P10','Alvin Kamara Jersey',60.50);
INSERT INTO product VALUES('P11','1 lb of Crawfish',4.00);
INSERT INTO product VALUES('P12','Jazz Fest Ticket',95.00);
INSERT INTO product VALUES('P13','1 lb of Boudin',5.99);
INSERT INTO product VALUES('P14','Streetcar Ticket',2.25);
INSERT INTO product VALUES('P15','Audubon Zoo Ticket',29.99);
INSERT INTO product VALUES('P16','1 Dozen Oysters',20.00);
INSERT INTO product VALUES('P17','Jazz at the Sandbar Ticket',0.00);
INSERT INTO product VALUES('P18','Snoball',3.99);
INSERT INTO product VALUES('P19','Frozen Coffee',9.99);
INSERT INTO product VALUES('P20','Saints Ticket',89.45);
COMMIT;
